---
title: "Введение в R. Осень 2018."
output: html_document
lang: ru-RU
---


* Семинар 1, 10 сентября. Загрузка и первое знакомство с данными
  
    - Условие и данные, [sem_010.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_010.zip)
    - [Решение семинара](http://bdemeshev.github.io/r_intro_3/seminar_010_solved.html)
    - [Решение домашней работы](http://bdemeshev.github.io/r_intro_3/hw_010_solutions.html)


* Семинар 2, 17 сентября. Качественные переменные, визуализация, ещё немного манипуляций с данными

    - Условие и данные, [sem_020.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_020.zip)
    - [Решение семинара](http://bdemeshev.github.io/r_intro_3/seminar_020_solved.html)
    - [Решение домашней работы](http://bdemeshev.github.io/r_intro_3/hw_020_solutions.html)
    - Большая библиотека всевозможных графиков: https://www.r-graph-gallery.com
    - [Курс](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1) на DataCamp по основнам работы с ggplot2


* Семинар 3, 24 сентября. Метод главных компонент

    - Условие и данные, [sem_030.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_030.zip)
    - [Решение семинара](http://bdemeshev.github.io/r_intro_3/seminar_030_solved.html)
    - [Решение домашней работы](http://bdemeshev.github.io/r_intro_3/hw_030_solutions.html)
    - [Визуализация](http://setosa.io/ev/principal-component-analysis/) метода главных компонент


* Семинар 4, 1 октября. Кластерный анализ

    - Условие и данные, [sem_040.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_040.zip)
    - [Решение семинара](http://bdemeshev.github.io/r_intro_3/seminar_040_solved.html)
    - [Решение домашней работы](http://bdemeshev.github.io/r_intro_3/hw_040_solutions.html)


* Семинар 5, 8 октября. Кластеризация — окончание.

    - Условие и данные, [sem_050.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_050.zip)
    



!!!15 октября занятий не будет

* Семинар 6, 22 октября. Маркдаун и красивое представление результатов.
    - Условие и данные, [sem_060.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_060.zip)
    - [Решение семинара](http://bdemeshev.github.io/r_intro_3/seminar_050_solved.html)


* Семинар 7, 29 октября. Логистическая регрессия и классификация.
    - Условие и данные, [sem_070.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_070.zip)
    - [Решение семинара](http://bdemeshev.github.io/r_intro_3/seminar_070_solved.html)

!!!5 ноября —  праздник

* Семинар 8, 12 ноября. Кросс-валидация.

    - Условие и данные, [sem_080.zip](https://github.com/bdemeshev/r_intro_3/raw/master/archives/sem_080.zip)



* Семинар 9, 19 ноября. Карты и ответы на вопросы :)


Место: Шаболовка 26, 5310. Приносите свои ноутбуки!!!
    

#### Финальное домашнее задание

Состоит из двух частей: курс на [DataCamp](https://www.datacamp.com/) и краткий анализ любого набора данных, [(минимальные требования)](http://bdemeshev.github.io/r_intro_3/hw_final.html).

* Стратегия 1: пройти курс [Communicating with data in tidyverse](https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse) на datacamp.com (4 балла) + полностью выполнить анализ набора данных по [заданию](http://bdemeshev.github.io/r_intro_3/hw_final.html) (6 баллов)

* Стратегия 2: пройти курс [Communicating with data in tidyverse](https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse) на datacamp.com (4 балла) + пройти ещё один любой курс по R на datacmp.com (4 балла) + выполнить упражнения из [задания](http://bdemeshev.github.io/r_intro_3/hw_final.html) на 2 балла (2 балла)

Важно! Формат сдачи задания по анализу данных — два файла, Rmd и html.

**Дедлайн**: 19 ноября


#### Полезности:


* Подборка [русскоязычных ресурсов](https://github.com/bdemeshev/r_links)
* Таблица с [пожелалками и комментариями](https://docs.google.com/spreadsheets/d/1ySFm0tvKH8-uNhNdkMub7l0D3b2FM-9Ud5Avs14yUaw/edit)
* Предыдущие реинкарнации курса: [раз](http://bdemeshev.github.io/r_socio_hse/) и [два](http://bdemeshev.github.io/r_intro_2/)


#### Перед первым занятием:

1. Установите [R + Rstudio по инструкции](http://bdemeshev.github.io/installation/r/R_installation.html)
1. Установите [дистрибутив Latex](https://www.tug.org/texlive/acquire-netinstall.html)
1. Установите [Github desktop](https://desktop.github.com/)
1. Зарегистрируйтесь на [datacamp.com](http://datacamp.com/)
1. Зарегистрируйтесь на [github.com](http://github.com/)

-------
Созданные для данного курса материалы распространяются по лицензии [Creative Commons Attribution-NonCommercial-ShareAlike](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.ru)
